config/routes.rb
Rails.application.routes.draw do
  get 'contact' => 'contacts#new'
  get 'contacts/create'
  get 'about' => 'about#index'

  namespace :admin do
  get "Log in" => "sessions#new", :as => "login"
  end

  namespace :admin do
  get "Log Out" => "sessions#destroy", :as => "logout"
  end

  namespace :admin do
  get 'sessions/create'
  end

  namespace :admin do
  get 'users/new'
  end

  namespace :admin do
  get 'users/create'
  end

  namespace :admin do
  get 'users/edit'
  end

  namespace :admin do
  get 'users/update'
  end

  namespace :admin do
  get 'users/destroy'
  end

  namespace :admin do
  get 'users/index'
  end

  namespace :admin do
  get 'users/show'
  end

  namespace :admin do
  get 'comments/destroy'
  end

  get 'comments/new'

  namespace :admin do
  get 'categories/new'
  end

  namespace :admin do
  get 'categories/create'
  end

  namespace :admin do
  get 'categories/edit'
  end

  namespace :admin do
  get 'categories/update'
  end

  namespace :admin do
  get 'categories/destroy'
  end

  namespace :admin do
  get 'categories/index'
  end

  namespace :admin do
  get 'categories/show'
  end

  get 'categories/show'

  namespace :admin do
  get 'posts/new'
  end

  namespace :admin do
  get 'posts/create'
  end

  namespace :admin do
  get 'posts/edit'
  end

  namespace :admin do
  get 'posts/update'
  end

  namespace :admin do
  get 'posts/destroy'
  end

  namespace :admin do
  get 'posts/index'
  end

  namespace :admin do
  get 'posts/show'
  end

  get 'posts/index'

  get 'posts/show'

  resources :posts, :categories
  resources "contacts", only: [:new, :create]
  
  namespace :admin do
    resources :posts, :categories, :comments, :users, :sessions
  end

  resources :posts do
    resources :comments
  end

  root 'posts#index'
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :posts

	validates :name, presence: true

	def self.search(query)
		where("name like ?", "%#{query}")
	end 
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :category
	belongs_to :user
	has_many :comments

	validates :title, presence: true
	validates :category_id, presence: true
	validates :body, presence: true

	has_attached_file :image, :defualt_url => ":style/news-1.png"
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

	def self.search(query)
		where("title like ? OR body like ?", "%#{query}", "%#{query}")
	end 
end

app/models/user.rb
class User < ActiveRecord::Base

	attr_accessor :password
	before_save :encrypt_password
	has_many :posts

	validates :name, presence: true
	validates :email, presence: true
	validates :password, presence: true
	validates :password, confirmation: true

	def self.authenticate(email, password)
		user = find_by_email(email)
			if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
				user
			else
			    nil
			end
 	end

	def encrypt_password
		if password.present?
			self.password_salt = BCrypt::Engine.generate_salt
			self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
		end
	end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
  	@post = Post.find(params[:post_id])
  	@comment = @post.comments.create(comment_params)

  	flash[:notice] = 'your comment has been added'

  	redirect_to post_path(@post)
  end

  private
  	def comment_params
  		params.require(:comment).permit(:name, :email, :body, :post_id)
  	end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
  end

  def create
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  	@posts = Post.all
  	@categories = Category.all
  end

  def show
  	@post = Post.find(params[:id])
  	@categories = Category.all
  	@comment = Comment.new
  	@comments = Comment.all
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_flash_message.html.erb
<% if flash[:notice] %>
<div class="alert alert-success"><%= flash[:notice] %></div>
<% end %>

<% if flash[:alert] %>
<div class="alert alert-danger"><%= flash[:alert] %></div>
<% end %>

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sitra</title>
  <%= stylesheet_link_tag    'admin/application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'admin/application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<!-- NAVIGATION -->
		<section>
			<div class="row">
				<div class="col-md-12 col-sm-12 col-xs-12">
					<div class="menu">
						<nav class="navbar navbar-default">
							<div class="container">
								<!-- Brand and toggle get grouped for better mobile display -->
								<div class="navbar-header">
									<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
										<span class="sr-only">Toggle navigation</span>
										<span class="icon-bar"></span>
										<span class="icon-bar"></span>
										<span class="icon-bar"></span>
									</button>
									<a class="navbar-brand" <%= link_to "Posts", admin_posts_path %> >
									<i class="img"><%= image_tag("logo.jpg") %></i> Si<span>Tra</span></a>
								</div>

								<!-- Collect the nav links, forms, and other content for toggling -->
								<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
									<ul class="nav navbar-nav navbar-right">
										<li class="<%= params[:controller] == 'admin/posts' ? 'active' : '' %>"><%= link_to "Posts", admin_posts_path %> </li>
										<li class="<%= params[:controller] == 'admin/categories' ? 'active' : '' %>"><%= link_to "Categories", admin_categories_path %></li>
										<li class="<%= params[:controller] == 'admin/users' ? 'active' : '' %>"><%= link_to "Users", admin_users_path %></li>
										
									</ul>
								</div> <!-- navbar-collapse -->
							</div> <!-- container-fluid -->
						</nav>
					</div>
				</div>
			</div>
		</section>
		<!-- END NAVIGATION -->
		<!--posts-->
        <div class="container">
	        <div class="row">
			<div class="col-md-12">
			<div id="user_nav" class="pull-right">
			    <% if current_user %>
			       	Logged in as <%= current_user.email %>
			       	<%= link_to "log out", admin_logout_path %>
			    <% else %>
			    	<%= link_to "log in", admin_login_path %>
			    <% end %>
            </div>
				<%= render 'layouts/flash_message' %>
				<%= yield %>
			</div> 	
	        </div>
        </div>
		<!--end-->
		<!-- TOP FOOTER -->
		<section class="top-footer">
			<div class="container">
				<div class="row">
					<div class="col-md-3">
						<div class="media">
							<div class="media-left"><a href="#"><i class="fa fa-home"></i></a></div>
							<div class="media-body">
								<h5 class="media-heading"></h5>
								<p></p>
							</div>
						</div>
					</div>
					<div class="col-md-3"> 
                    <div class="media">
							<div class="media-left">
								<a href="#"><i class="fa fa-envelope-o"></i></a>
							</div>
							<div class="media-body">
								<h5 class="media-heading"></h5>
								<p></p>
							</div>
						</div>
                    </div>
						
					<div class="col-md-3">
						<div class="media">
							<div class="media-left">
								<a href="#"><i class="fa fa-phone"></i></a>
							</div>
							<div class="media-body">
								<h5 class="media-heading"></h5>
								<p></p>
							</div>
						</div>
					</div>
					<div class="col-md-3">
						<div class="media">
							<div class="media-left">
								<a href="#"><i class="fa fa-phone"></i></a>
							</div>
							<div class="media-body">
								Sitra Consultancy Firm | <%= link_to 'frontend', root_path, target: '_blank' %>
							</div>
						</div>
			</div>
		</section>
		<!-- END TOP FOOTER -->
	
		<!-- BOTTOM FOOTER -->
		<section class="bottom-footer">
			<div class="container">
				<div class="row">
					<div class="col-md-6">
						Copyrights 2016 All Reseved by <a href="sitra.co.ke">Sitra.co.ke</a>
					</div>
					<div class="col-md-6 text-right">
						<a href="#">Terms of use</a>
						<a href="#">Privacy & Security Statement</a>
					</div>
				</div>
			</div>
		</section>
		<!-- END BOTTOM FOOTER -->
</body>
</html>

app/views/layouts/admin/login.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Login | Sitra</title>
  <%= stylesheet_link_tag    'admin/mystyle', media: 'all', 'data-turbolinks-track' => true %>
  
</head>
<body>
<div class="container">
	<%= yield %>
</div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Al-amin Academy</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<!-- NAVIGATION -->
		<section style="margin-top: -4rem;">
			<div class="row">
				<div class="col-md-12 col-sm-12 col-xs-12">
					<div class="menu">
						<nav class="navbar navbar-default">
							<div class="container">
								<!-- Brand and toggle get grouped for better mobile display -->
								<div class="navbar-header">
									<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
										<span class="sr-only">Toggle navigation</span>
										<span class="icon-bar"></span>
										<span class="icon-bar"></span>
										<span class="icon-bar"></span>
									</button>
									<a class="navbar-brand" href="#"><i class="img"><%= image_tag("logo.png") %></i> </a><a style="font-size: 2rem;">Al-amin Integ<span>rated Academy</span></a>
								</div>

								<!-- Collect the nav links, forms, and other content for toggling -->
								<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
									<ul class="nav navbar-nav navbar-right" style="margin-top: 1rem;" >
										<li class="<%= params[:controller] == 'Home' ? 'active' : '' %>" ><%= link_to "Home", root_path %> </li>
										<li class="<%= params[:controller] == 'About' ? 'active' : '' %>"><%= link_to "About Us", about_path %></li>
										<li class="<%= params[:controller] == 'Contact' ? 'active' : '' %>"><%= link_to "Contact", contact_path %></li>
										
									</ul>
								</div> <!-- navbar-collapse -->
							</div> <!-- container-fluid -->
						</nav>
					</div>
				</div>
			</div>
		</section>
		<!-- END NAVIGATION -->
       <!--alert massages-->
       <%= render 'layouts/flash_message' %>
		<%= yield %>
		<!-- TOP FOOTER -->
		<section class="top-footer">
			<div class="container">
				<div class="row">
					<div class="col-md-3">
						<div class="media">
							<div class="media-left"><a href="#"><i class="fa fa-home"></i></a></div>
							<div class="media-body">
								<h5 class="media-heading"></h5>
								<p>location</p>
							</div>
						</div>
					</div>
					<div class="col-md-3">
                    <div class="media">
							<div class="media-left">
								<a href="#"><i class="fa fa-envelope-o"></i></a>
							</div>
							<div class="media-body">
								<h5 class="media-heading">Having any questions?</h5>
								<p>email</p>
							</div>
						</div>
                    </div>
						
					<div class="col-md-3">
						<div class="media">
							<div class="media-left">
								<a href="#"><i class="fa fa-phone"></i></a>
							</div>
							<div class="media-body">
								<h5 class="media-heading">Call us & Hair us</h5>
								<p>phone numbers</p>
								
							</div>
						</div>
					</div>
					<div class="col-md-3">
						<div class="media">
							<div class="media-left">
								
							</div>
							<div class="media-body">
								<p>Al-amin academy | <%= link_to "log in", admin_login_path %></p>
							</div>
						</div>
			</div>
		</section>
		<!-- END TOP FOOTER -->
</body>
</html>

app/views/partials/_comments.html.erb
<div class="container">
	<h2 class="page-header"><%= @post.comments.length %> Comments</h2>
	<% @post.comments.each do | comment| %>
	<div class="comment">
		<div class="row">
			<div class="col-md-12">
				<div class="well">
				<h4><%= comment.name%> <span>/<%= comment.created_at.to_time.strftime('%B, %e at %l:%M %p') %></span></h4>
				<%= comment.body %>
				</div>
			</div>
		</div>
	</div>
	<% end %>
	<div class="well add-comment">
		<h2 class="page-header">Add Comments</h2>
		<%= form_for([@post, @post.comments.build]) do |f| %>
		<div class="form-group">
		<%= f.label :name %><br>
		<%= f.text_field :name, class: 'form-control' %>
		</div>

		<div class="form-group">
		<%= f.label :email %><br>
		<%= f.text_field :email, class: 'form-control' %>
		</div>

		<div class="form-group">
		<%= f.label :body %><br>
		<%= f.text_field :body, class: 'form-control' %>
		</div>
		<div class="form-group">
		<%= f.submit  "submit", class: 'btn btn-primary' %>
		</div>
		<% end %>
	</div>
</div>